{{- if .Values.archestra.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "archestra-platform.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archestra-platform.labels" . | nindent 4 }}
  {{- with .Values.archestra.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.archestra.ingress.spec }}
  {{- toYaml .Values.archestra.ingress.spec | nindent 2 }}
  {{- else }}
  {{- if .Values.archestra.ingress.tls }}
  tls:
    {{- range .Values.archestra.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.archestra.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- else }}
            pathType: Prefix
            {{- end }}
            backend:
              service:
                name: {{ include "archestra-platform.fullname" $ }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}